/* Anahtar tabanlı çeviri. Web sürümündeki sözlük yaklaşımı yerine
   burada doğrudan anahtar kullanıldı — yeni metin eklemek daha güvenli. */
export const STR = {
  tr: {
    appName: 'BetLedger',
    // sekmeler
    tabHome: 'Genel', tabBets: 'Bahisler', tabAdd: 'Ekle', tabStats: 'Analiz', tabAcc: 'Hesap',
    // kurulum
    obTitle1: 'Bu uygulama ne yapar?',
    obLead1: 'Bahis önermez, tahmin üretmez. Yaptığın bahisleri kaydeder, kasanı hesaplar ve zamanla nasıl bahis yaptığını gösterir.',
    obP1a: 'Kuponlarını kaydet', obP1b: 'Maç, bahis türü, oran ve tutarı gir. Maç bitince sonucu işaretle.',
    obP2a: 'Kasan kendi kendine işler', obP2b: 'Tutar düşülür, sonuç girildiğinde kazanç eklenir.',
    obP3a: 'Davranışını da ölçer', obP3b: 'Risk sınırını aştığında ve kayıp sonrası tutarı büyüttüğünde uyarır.',
    obTitle2: 'Başlangıç kasan', obLead2: 'Bahis için ayırdığın toplam parayı gir.',
    obTitle3: 'Kupon başına ne kadar?',
    obLead3: 'Kasanı eşit dilimlere böl. Dilim büyüdükçe kasan iki yöne de hızlı hareket eder.',
    obTitle4: 'Hazırsın', obLead4: 'Dört sekme var: Genel, Bahisler, Analiz, Hesap. Ortadaki buton kupon ekler.',
    amount: 'Tutar', currency: 'Para birimi', unitValue: '1 birim değeri',
    riskLimit: 'Tek kuponda en fazla (%)',
    next: 'Devam', back: 'Geri', start: 'Başla', skip: 'Kurulumu atla',
    // pano
    bankroll: 'Kasa', available: 'Kullanılabilir', openBets: 'Açık bahis',
    today: 'Bugün', staked: 'Yatırım', result: 'Sonuç', discipline: 'Disiplin',
    fromPeak: 'Zirveden', addBet: 'Bahis ekle', todayAlert: 'Bugünün uyarısı',
    noPending: 'Bekleyen bahsin yok.', noSignals: 'Şu an tetiklenen kural yok.',
    takeBreak: 'Mola ver', breakOn: 'Mola sürüyor', cancelBreak: 'Molayı iptal et',
    disclaimer: 'Bu araç bahis önermez, tahmin üretmez, kupon oluşturmaz. Yalnızca senin girdiğin veriyi ölçer.',
    // bahisler
    allBets: 'Tümü', pending: 'Bekleyen', won: 'Kazandı', lost: 'Kaybetti', voided: 'İptal',
    single: 'Tek', parlay: 'Kombine', odds: 'Oran', stake: 'Bahis tutarı',
    potential: 'Muhtemel getiri', pl: 'Kâr / zarar', status: 'Durum',
    noMatch: 'Bu filtreyle eşleşen kupon yok.', periodStats: 'Dönem istatistikleri',
    // kupon ekleme
    newBet: 'Yeni kupon', home: 'Ev sahibi', away: 'Deplasman', league: 'Lig',
    market: 'Bahis türü', note: 'Not (isteğe bağlı)', addSelection: 'Seçim ekle',
    removeSelection: 'Kaldır', save: 'Onayla ve kaydet', cancel: 'Vazgeç',
    preCheck: 'Bahis öncesi kontrol', withinLimits: 'Belirlediğin sınırların içinde',
    overLimit: 'sınır aşılıyor', shareEquity: 'Toplam kasaya oranı',
    shareAvail: 'Kullanılabilir bakiyeye oranı', todayCount: 'Bugünkü bahis sayısı',
    todayStake: 'Bugünkü toplam yatırım', lockedOpen: 'Açık bahislerde kilitli',
    last5: 'Son 5 kupon', last10: 'Son 10 kupon', limit: 'sınır',
    whyBet: 'Bu bahsi neden yapıyorsun?',
    rStat: 'İstatistiğe dayanıyor', rValue: 'Değer gördüm', rFun: 'Eğlence',
    rChase: 'Kaybı telafi', rUnsure: 'Emin değilim', rOther: 'Diğer',
    chaseWarn: 'Kaybı telafi için oynanan bahisler, kayıp kovalamanın en yaygın başlangıcıdır.',
    pickReason: 'Bahsi neden yaptığını seç',
    needTeams: 'Takım isimleri boş olamaz', needAmount: 'Tutar sıfırdan büyük olmalı',
    notEnough: 'Harcanabilir bakiye yetersiz',
    // kupon detayı
    couponDetail: 'Kupon', markResult: 'Sonucu işaretle', undo: 'Sonucu geri al',
    reason: 'Gerekçe', saved: 'Kupon kaydedildi', resultSaved: 'Sonuç kaydedildi',
    // analiz
    summary: 'Özet', profile: 'Profilim', roi: 'Getiri oranı', strike: 'İsabet oranı',
    net: 'Net sonuç', avgOdds: 'Ortalama oran', coupons: 'Kupon',
    totalStaked: 'Toplam yatırım', totalWin: 'Toplam kazanç', totalLoss: 'Toplam kayıp',
    avgStake: 'Ortalama yatırım', bestWin: 'En yüksek kazanç', worstLoss: 'En yüksek kayıp',
    winRun: 'En uzun kazanma serisi', lossRun: 'En uzun kayıp serisi',
    drawdown: 'En büyük düşüş', peak: 'En yüksek kasa', current: 'Mevcut kasa',
    dailyPl: 'Günlük kâr / zarar', last14: 'son 14 gün', findings: 'Bulgular',
    behaviour: 'Davranış sinyalleri', notEnoughData: 'Yeterli veri yok',
    period7: '7 gün', period30: '30 gün', period90: '90 gün', periodAll: 'Tümü',
    // hesap
    settings: 'Ayarlar', addFunds: 'Para ekle', withdraw: 'Para çek',
    activity: 'Hesap hareketleri', badges: 'Rozetler', unlocked: 'açık',
    appearance: 'Görünüm', langLabel: 'Dil', themeLight: 'Açık', themeDark: 'Koyu',
    notifications: 'Bildirimler', allowNotif: 'Bildirimlere izin ver',
    notifOn: 'Bildirimler açık', notifOff: 'İzin vermezsen bildirimler yalnızca uygulamada görünür.',
    sampleData: 'Örnek veri yükle', wipe: 'Tüm verileri sil',
    wipeConfirm: 'Tüm kayıtların silinecek. Emin misin?', wiped: 'Tüm veriler silindi',
    responsible: 'Sorumlu kullanım',
    respBody: 'Bu uygulama bahis oynatmaz, oran sunmaz, tahmin üretmez. 18 yaşından küçükler kullanamaz.',
    respHelp: 'Zorlandığını düşünüyorsan Yeşilay Danışmanlık Merkezi\'nin 115 numaralı hattı 7/24 ücretsiz destek veriyor.',
    dataNote: 'Verilerin yalnızca bu cihazda saklanır. Sunucuya gönderilmez.',
    noOcr: 'Kupon okuma bu sürümde yok; bilgileri elle giriyorsun.',
    minutes: 'dakika',
    ocrPick: "Kupon görüntüsü seç",
    ocrManual: "Bilgileri elle gir",
    ocrReading: "Kupon okunuyor",
    ocrHint: "Ekran görüntüsü fotoğraftan çok daha iyi sonuç verir",
    ocrFirst: "İlk okumada motor indiriliyor, birkaç saniye sürebilir",
    ocrFail: "Kupon okunamadı",
    ocrFailBody: "Görüntüde maç satırı tanınamadı. Bilgileri elle girebilirsin.",
    ocrNoModule: "Kupon okuma bu derlemede yok. Geliştirme derlemesi kurulduğunda çalışır.",
    ocrNoNet: "Okuma motoru indirilemedi. İlk kullanım için internet gerekiyor.",
    ocrRetry: "Başka görüntü dene",
    ocrFound: "Okunan bilgiler",
    ocrConfirm: "Onaylamadan hiçbir şey kaydedilmez.",
    ocrPriv: "Görüntü telefonundan çıkmaz, okuma cihazda yapılır.",
    permPhoto: "Fotoğraf izni verilmedi",
    journal: "Bahis günlüğü",
    jWhy: "Bu bahsi neden yaptım?",
    jExpect: "Ne olmasını bekliyordum?",
    jResult: "Sonuç neden böyle geldi?",
    jMistake: "Bir hata yaptım mı?",
    jAgain: "Yine oynar mıydım?",
    yes: "Evet",
    no: "Hayır",
    maybe: "Emin değilim",
    writeJournal: "Günlük yaz",
    journalSaved: "Günlük kaydedildi",
    breakdowns: "Dağılımlar",
    lab: "Laboratuvar",
    scenarios: "Senaryolar",
    dimOdds: "Oran aralığı",
    dimMarket: "Bahis türü",
    dimLeague: "Lig",
    dimType: "Tekli / kombine",
    dimHour: "Günün saati",
    dimDay: "Haftanın günü",
    dimStake: "Bahis tutarı",
    dimRisk: "Risk yüzdesi",
    needMore: "Karşılaştırma için grup başına en az 20 kupon gerekiyor.",
    labBank: "Başlangıç kasası",
    labOdds: "Ortalama oran",
    labRisk: "Bahis başına risk (%)",
    labBets: "Bahis sayısı",
    labWin: "Tahmini isabet (%)",
    labMedian: "Ortanca",
    labMean: "Ortalama",
    labBest: "En iyi",
    labWorst: "En kötü",
    labRuin25: "Çeyreğe düşme ihtimali",
    labRuin50: "Yarıya inme ihtimali",
    labRun3: "3 kayıplık seri",
    labRun5: "5 kayıplık seri",
    labRun10: "10 kayıplık seri",
    labNote: "Bunlar gelecek tahmini değildir. Girdiğin varsayımların 400 kez tekrarlanmasıyla üretilmiş olasılık dağılımıdır.",
    wiSingles: "Kombine yerine tekli",
    wiRisk: "Farklı risk yüzdesi",
    wiOdds: "Yüksek oranları çıkar",
    wiWorst: "En kötü türü çıkar",
    wiReal: "Gerçek sonuç",
    wiAlt: "Alternatif",
    wiDiff: "fark",
    wiNote: "Bu bir simülasyondur. Geçmiş verin üzerinde kurgusal bir değişiklik yapılmıştır.",
    notifAsk: "Bildirimlere izin ver",
    notifGranted: "Bildirimler açık",
    breakScheduled: "Mola bitince bildirim gelecek",
    searchMarket: 'Bahis türü ara',
    emptyOpenBody: 'Sonuçlanmamış kuponun yok. Kupon eklediğinde burada görünür ve sonucu tek dokunuşla işaretlersin.',
    emptyBetsBody: 'Bu filtrede kupon yok. Filtreyi değiştir ya da yeni kupon ekle.',
    longPressHint: 'Sonucu hızlı işaretlemek için karta basılı tut',
    streakNote: 'Üst üste kazanç ve kayıp serilerinin kasana etkisi. Kayıp her zaman tutarın tamamıdır, kazanç orana bağlıdır.'
  },
  en: {
    appName: 'BetLedger',
    tabHome: 'Home', tabBets: 'Bets', tabAdd: 'Add', tabStats: 'Analysis', tabAcc: 'Account',
    obTitle1: 'What does this app do?',
    obLead1: 'It gives no tips and makes no predictions. It records your bets, works out your bankroll and shows how you bet over time.',
    obP1a: 'Record your bets', obP1b: 'Enter the match, bet type, odds and stake. Mark the result when it ends.',
    obP2a: 'Your bankroll runs itself', obP2b: 'The stake is deducted and the return added when you enter the result.',
    obP3a: 'It measures your behaviour', obP3b: 'It warns you when you exceed your limit or raise your stake after a loss.',
    obTitle2: 'Your starting bankroll', obLead2: 'Enter the total money set aside for betting.',
    obTitle3: 'How much per coupon?',
    obLead3: 'Split your bankroll into equal slices. Bigger slices move it faster in both directions.',
    obTitle4: 'You are ready', obLead4: 'Four tabs: Home, Bets, Analysis, Account. The centre button adds a coupon.',
    amount: 'Amount', currency: 'Currency', unitValue: 'Value of 1 unit',
    riskLimit: 'Max per coupon (%)',
    next: 'Continue', back: 'Back', start: 'Start', skip: 'Skip setup',
    bankroll: 'Bankroll', available: 'Available', openBets: 'Open bets',
    today: 'Today', staked: 'Staked', result: 'Result', discipline: 'Discipline',
    fromPeak: 'From peak', addBet: 'Add bet', todayAlert: "Today's alert",
    noPending: 'You have no pending bets.', noSignals: 'No rules are currently triggered.',
    takeBreak: 'Take a break', breakOn: 'Break in progress', cancelBreak: 'Cancel the break',
    disclaimer: 'This tool gives no tips, makes no predictions and builds no coupons. It only measures the data you enter.',
    allBets: 'All', pending: 'Pending', won: 'Won', lost: 'Lost', voided: 'Void',
    single: 'Single', parlay: 'Accumulator', odds: 'Odds', stake: 'Stake',
    potential: 'Potential return', pl: 'Profit / loss', status: 'Status',
    noMatch: 'No coupons match this filter.', periodStats: 'Period summary',
    newBet: 'New coupon', home: 'Home', away: 'Away', league: 'League',
    market: 'Bet type', note: 'Note (optional)', addSelection: 'Add selection',
    removeSelection: 'Remove', save: 'Confirm and save', cancel: 'Cancel',
    preCheck: 'Pre-bet check', withinLimits: 'Within the limits you set',
    overLimit: 'limits exceeded', shareEquity: 'Share of total bankroll',
    shareAvail: 'Share of available balance', todayCount: 'Bets placed today',
    todayStake: 'Total staked today', lockedOpen: 'Locked in open bets',
    last5: 'Last 5 coupons', last10: 'Last 10 coupons', limit: 'limit',
    whyBet: 'Why are you placing this bet?',
    rStat: 'Based on statistics', rValue: 'I saw value', rFun: 'For fun',
    rChase: 'To recover a loss', rUnsure: 'Not sure', rOther: 'Other',
    chaseWarn: 'Bets placed to recover a loss are the most common start of chasing.',
    pickReason: 'Choose why you are placing this bet',
    needTeams: 'Team names cannot be empty', needAmount: 'The amount must be greater than zero',
    notEnough: 'Not enough available balance',
    couponDetail: 'Coupon', markResult: 'Mark the result', undo: 'Undo result',
    reason: 'Reason', saved: 'Bet saved', resultSaved: 'Result saved',
    summary: 'Summary', profile: 'My profile', roi: 'ROI', strike: 'Strike rate',
    net: 'Net result', avgOdds: 'Average odds', coupons: 'Coupons',
    totalStaked: 'Total staked', totalWin: 'Total winnings', totalLoss: 'Total losses',
    avgStake: 'Average stake', bestWin: 'Biggest win', worstLoss: 'Biggest loss',
    winRun: 'Longest winning run', lossRun: 'Longest losing run',
    drawdown: 'Maximum drawdown', peak: 'Highest bankroll', current: 'Current bankroll',
    dailyPl: 'Daily profit / loss', last14: 'last 14 days', findings: 'Findings',
    behaviour: 'Behaviour signals', notEnoughData: 'Not enough data',
    period7: '7 days', period30: '30 days', period90: '90 days', periodAll: 'All',
    settings: 'Settings', addFunds: 'Add funds', withdraw: 'Withdraw',
    activity: 'Account activity', badges: 'Badges', unlocked: 'unlocked',
    appearance: 'Appearance', langLabel: 'Language', themeLight: 'Light', themeDark: 'Dark',
    notifications: 'Notifications', allowNotif: 'Allow notifications',
    notifOn: 'Notifications are on', notifOff: 'Without permission, alerts appear only in the app.',
    sampleData: 'Load sample data', wipe: 'Delete all data',
    wipeConfirm: 'All your records will be deleted. Are you sure?', wiped: 'All data deleted',
    responsible: 'Responsible use',
    respBody: 'This app takes no bets, shows no odds and makes no predictions. Not for anyone under 18.',
    respHelp: 'If you are struggling, the Yeşilay Counselling Centre helpline on 115 is free, 24/7.',
    dataNote: 'Your data is stored only on this device. Nothing is sent to a server.',
    noOcr: 'Coupon reading is not in this build; you enter the details manually.',
    minutes: 'minutes',
    ocrPick: "Choose a coupon image",
    ocrManual: "Enter details manually",
    ocrReading: "Reading the coupon",
    ocrHint: "A screenshot works far better than a photo",
    ocrFirst: "The engine downloads on first use; it can take a few seconds",
    ocrFail: "Could not read the coupon",
    ocrFailBody: "No match line was recognised. You can enter the details manually.",
    ocrNoModule: "Coupon reading is not in this build. It works once the development build is installed.",
    ocrNoNet: "The reading engine could not be downloaded. First use needs internet.",
    ocrRetry: "Try another image",
    ocrFound: "What we read",
    ocrConfirm: "Nothing is saved until you confirm.",
    ocrPriv: "The image never leaves your phone; reading happens on the device.",
    permPhoto: "Photo permission was not granted",
    journal: "Bet journal",
    jWhy: "Why did I place this bet?",
    jExpect: "What did I expect?",
    jResult: "Why did it turn out this way?",
    jMistake: "Did I make a mistake?",
    jAgain: "Would I place it again?",
    yes: "Yes",
    no: "No",
    maybe: "Not sure",
    writeJournal: "Write journal",
    journalSaved: "Journal saved",
    breakdowns: "Breakdowns",
    lab: "Lab",
    scenarios: "Scenarios",
    dimOdds: "Odds range",
    dimMarket: "Bet type",
    dimLeague: "League",
    dimType: "Single / accumulator",
    dimHour: "Time of day",
    dimDay: "Day of week",
    dimStake: "Stake size",
    dimRisk: "Risk %",
    needMore: "Comparison needs at least 20 coupons per group.",
    labBank: "Starting bankroll",
    labOdds: "Average odds",
    labRisk: "Risk per bet (%)",
    labBets: "Number of bets",
    labWin: "Estimated strike rate (%)",
    labMedian: "Median",
    labMean: "Mean",
    labBest: "Best",
    labWorst: "Worst",
    labRuin25: "Chance of falling to a quarter",
    labRuin50: "Chance of halving",
    labRun3: "Run of 3 losses",
    labRun5: "Run of 5 losses",
    labRun10: "Run of 10 losses",
    labNote: "These are not predictions. It is a probability distribution from repeating your assumptions 400 times.",
    wiSingles: "Singles instead of accas",
    wiRisk: "A different risk %",
    wiOdds: "Remove high odds",
    wiWorst: "Remove worst bet type",
    wiReal: "Actual",
    wiAlt: "Alternative",
    wiDiff: "difference",
    wiNote: "This is a simulation. A hypothetical change has been applied to your past data.",
    notifAsk: "Allow notifications",
    notifGranted: "Notifications are on",
    breakScheduled: "You will be notified when the break ends",
    searchMarket: 'Search bet type',
    emptyOpenBody: 'No unsettled coupons. Once you add one it appears here and you mark the result in a single tap.',
    emptyBetsBody: 'No coupons in this filter. Change the filter or add a new one.',
    longPressHint: 'Long-press a coupon to mark the result quickly',
    streakNote: 'What runs of wins and losses do to your bankroll. A loss is always the whole stake; a win depends on the odds.'
  }
};

export const makeT = lang => k => (STR[lang] && STR[lang][k]) || STR.tr[k] || k;
